#!/bin/bash

P_DIR=$HOME/1/bash
source $P_DIR/pred/paths.sh

pidof watch | xargs kill

# nohup watch -n 8 $WATCH_PATH/scripts_update.sh >/dev/null 2>&1 &
# nohup watch -n 4 $WATCH_PATH/docs_update.sh >/dev/null 2>&1 &

echo "execute from $WATCH_PATH"
xfce4-terminal -e "watch -n 16 $WATCH_PATH/scripts_update.sh"
xfce4-terminal -e "watch -n 10 $WATCH_PATH/docs_update.sh"

xfce4-terminal -e "watch -n 2 $PRED_PATH/ac_log.sh"



